### ISSUE TITLE
I HAVE A BIG ERROR...

### ISSUE THREAD

**Issue by LeChevalierDOr** [gabizou/HappyTrails#5]
Hello,

When i trying to start my server minecraft in 1.12.2 SPONGE FORGE (7.1.0-BETA-3392 / Forge 14.23.4.2705)

I get this error :
```
[20:44:10] [Server thread/ERROR] [Sponge]: Could not pass SpongeGameRegistryRegisterEvent to Plugin{id=happytrails, name=HappyTrails, version=0.1.4, description=A fancy plugin making trails for players to use, url=https://gabizou.com/, authors=[gabizou], source=/var/directory_serv/minecraft_182843/./plugins/HappyTrails-0.1.4.jar}
java.lang.IllegalArgumentException: A plugin is trying to this.register custom keys under a different plugin id namespace! This is unsupported! The provided key: happytrails:trail
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[minecraft_server.1.12.2.jar:?]
	at org.spongepowered.common.registry.type.data.KeyRegistryModule.registerAdditionalCatalog(KeyRegistryModule.java:636) ~[KeyRegistryModule.class:1.12.2-2705-7.1.0-BETA-3392]
	at org.spongepowered.common.registry.type.data.KeyRegistryModule.registerAdditionalCatalog(KeyRegistryModule.java:65) ~[KeyRegistryModule.class:1.12.2-2705-7.1.0-BETA-3392]
	at org.spongepowered.common.event.registry.SpongeGameRegistryRegisterEvent.register(SpongeGameRegistryRegisterEvent.java:59) ~[SpongeGameRegistryRegisterEvent.class:1.12.2-2705-7.1.0-BETA-3392]
	at com.gabizou.happytrails.HappyTrails.registerKeys(HappyTrails.java:138) ~[HappyTrails.class:?]
	at org.spongepowered.common.event.listener.RegisterListener_HappyTrails_registerKeys58.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2705-7.1.0-BETA-3392]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3392]
	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:443) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3392]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3392]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:447) [SpongeEventManager.class:1.12.2-2705-7.1.0-BETA-3392]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:225) [SpongeImpl.class:1.12.2-2705-7.1.0-BETA-3392]
	at org.spongepowered.common.registry.SpongeGameRegistry.throwRegistryEvent(SpongeGameRegistry.java:609) [SpongeGameRegistry.class:1.12.2-2705-7.1.0-BETA-3392]
	at org.spongepowered.common.registry.SpongeGameRegistry.registerModulePhase(SpongeGameRegistry.java:535) [SpongeGameRegistry.class:1.12.2-2705-7.1.0-BETA-3392]
	at org.spongepowered.common.registry.SpongeGameRegistry.init(SpongeGameRegistry.java:564) [SpongeGameRegistry.class:1.12.2-2705-7.1.0-BETA-3392]
	at org.spongepowered.mod.SpongeMod.onInitialization(SpongeMod.java:384) [SpongeMod.class:1.12.2-2705-7.1.0-BETA-3392]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
```

Please HELP ME !
Thanks you in advance !

**Comment by gabizou** [comment]
Update the plugin. I made a new release fixing this 6 days ago.
